### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by Redirect0null** [taras42/report_telegram_channels#5]
Docker show an error 

![image](https://user-images.githubusercontent.com/100712266/156217357-85ea930c-a3b7-492a-b539-f9d2850d34a2.png)

**Comment by taras42** [comment]
There might be some issues on Windows machines. You can try doing this (can't investigate on a Windows machine at the moment):

```
DOCKER_BUILDKIT=0 docker build . -t report-telegram
```
If it builds successfully, then the run command should work without issues.

**Comment by taras42** [comment]
The line above will fix the build on Windows. Added it to README.
